'ReCiPe 2016 v1.03, endpoint (H) - ecosystem quality - climate change: freshwater ecosystems - incl. H and bio CO2':
- mining and basic metals
'ReCiPe 2016 v1.03, endpoint (H) - ecosystem quality - climate change: terrestrial ecosystems - incl. H and bio CO2':
- mining and basic metals
'ReCiPe 2016 v1.03, endpoint (H) - human health - climate change: human health - incl. H and bio CO2':
- mining and basic metals
'ReCiPe 2016 v1.03, endpoint (H) no LT - ecosystem quality no LT - climate change: freshwater ecosystems no LT - incl. H and bio CO2 no LT':
 - mining and basic metals
'ReCiPe 2016 v1.03, endpoint (H) no LT - ecosystem quality no LT - climate change: terrestrial ecosystems no LT - incl. H and bio CO2 no LT':
 - mining and basic metals
'ReCiPe 2016 v1.03, endpoint (H) no LT - human health no LT - climate change: human health no LT - incl. H and bio CO2 no LT':
 - mining and basic metals
'RELICS - metals extraction - Lead':
- mining and basic metals
